### PR TITLE
class 09 issues and refactor

### PR DESCRIPTION
**Pull request by derekmhewitt**

### CODE REVIEW

**Comment by derekmhewitt** [comment]
Rather than make a change in every file I'd like to refactor I'm simply going to make comments on this pull request about the changes I'd like to make, then I'll be making those changes.

**Comment by derekmhewitt** [comment]
app.js issues
- <s>clean up extra constructedArticles variable
- wrap contents in an iffy
- modify the ArticleConstructor function so it doesn't use a 'for in' loop anymore</s>
- maybe add persistent storage, checking against the eTag so I only pull in new data if the old data has changed

**Comment by derekmhewitt** [comment]
indexPageUtil.js issues
- <s>wrap contents in an iffy</s>
- change hamburger icon to an x while it's open, and maybe animate the menu (if I have time)

**Comment by derekmhewitt** [comment]
css and html

<s>some minor comment clean up maybe but I think these are all pretty tidy already. </s>

**Comment by loganlsr** [comment]
Since you have made your sourceData into a JSON file, I don't believe you need the sourceData.js file anymore.

**Comment by loganlsr** [comment]
Responsiveness is nice, and I like that you have multiple levels of change depending on screen size. 

When viewing your page in Ipad size, the image doesn't really fit the look of the page. I might change the threshold for your first change from 800px to maybe like 700px or 750px, just to get that image that would fit better on that size screen.

Also not sure if you want to have the nav bar showing or if you would rather have a hamburger menu on the Ipad screen size.

**Comment by loganlsr** [comment]
You code looks clean and concise!  Everything is named in an understandable way.

**Pull request merged**
